import type { AskShirleyCategory, AskShirleyQuestion } from "./types";

export type { AskShirleyCategory, AskShirleyQuestion };

export const ASK_SHIRLEY_CATEGORIES: { id: AskShirleyCategory; label: string }[] = [
  { id: "all", label: "All Questions" },
  { id: "design", label: "Design & Philosophy" },
  { id: "projects", label: "Projects" },
  { id: "ai", label: "AI & Technology" },
  { id: "research", label: "Research" },
  { id: "creative", label: "Creative Process" },
  { id: "career", label: "Career & Work" },
  { id: "personal", label: "Personal" },
];

export const ASK_SHIRLEY_QUESTIONS: AskShirleyQuestion[] = [
  {
    id: "personal-project",
    number: "01",
    text: "What makes a project feel personal to you?",
    category: "design",
  },
  {
    id: "bold-vs-random",
    number: "02",
    text: "What is the difference between bold design and random design?",
    category: "design",
  },
  {
    id: "coherence",
    number: "03",
    text: "Why do you care so much about coherence?",
    category: "design",
  },
  {
    id: "boring-interface",
    number: "04",
    text: "What makes an interface feel boring?",
    category: "design",
  },
  {
    id: "tech-impressive-weak",
    number: "05",
    text: "What makes something technically impressive but experientially weak?",
    category: "design",
  },
  {
    id: "idea-working",
    number: "06",
    text: "How do you decide when an idea is actually working?",
    category: "design",
  },
  {
    id: "first-version-wrong",
    number: "07",
    text: "How do you respond when the first version of something is wrong?",
    category: "design",
  },
  {
    id: "misunderstand-design",
    number: "08",
    text: "What do you think people misunderstand about good design?",
    category: "design",
  },
  {
    id: "originality",
    number: "09",
    text: "What does originality mean to you?",
    category: "design",
  },
  {
    id: "intuition-evidence",
    number: "10",
    text: "How do you balance intuition with evidence?",
    category: "design",
  },
  {
    id: "portfolio-dialects",
    number: "11",
    text: "Why do you want each portfolio page to look different?",
    category: "design",
  },
  {
    id: "memorable-portfolio",
    number: "12",
    text: "What do you think makes a portfolio memorable?",
    category: "design",
  },
  {
    id: "design-principles",
    number: "13",
    text: "What design principles guide your work?",
    category: "design",
  },
  {
    id: "minimalism",
    number: "14",
    text: "Do you like minimalism?",
    category: "design",
  },
  {
    id: "ai-interest",
    number: "15",
    text: "What interests you about AI?",
    category: "ai",
  },
  {
    id: "shallow-ai",
    number: "16",
    text: "What kinds of AI products feel shallow to you?",
    category: "ai",
  },
  {
    id: "good-ai-design",
    number: "17",
    text: "What does good AI interaction design mean?",
    category: "ai",
  },
  {
    id: "ai-pretend-human",
    number: "18",
    text: "Should AI pretend to be human?",
    category: "ai",
  },
  {
    id: "ai-enjoy-building",
    number: "19",
    text: "What parts of AI systems do you most enjoy building?",
    category: "ai",
  },
  {
    id: "agents-automation",
    number: "20",
    text: "How do you think about agents and automation?",
    category: "ai",
  },
  {
    id: "ai-trustworthy",
    number: "21",
    text: "What makes an AI system trustworthy?",
    category: "ai",
  },
  {
    id: "ai-never-answer",
    number: "22",
    text: "What should AI never answer on your behalf?",
    category: "ai",
  },
  {
    id: "uncertainty-ai",
    number: "23",
    text: "What role should uncertainty play in an AI response?",
    category: "ai",
  },
  {
    id: "tech-art",
    number: "24",
    text: "How do you think about the relationship between technology and art?",
    category: "ai",
  },
  {
    id: "proud-projects",
    number: "25",
    text: "What projects are you most proud of and why?",
    category: "projects",
  },
  {
    id: "represents-best",
    number: "26",
    text: "Which project represents you best and why?",
    category: "projects",
  },
  {
    id: "why-echo",
    number: "27",
    text: "Why did you build Echo?",
    category: "projects",
  },
  {
    id: "echo-learn",
    number: "28",
    text: "What did you learn from building Echo?",
    category: "projects",
  },
  {
    id: "nommi-inspire",
    number: "29",
    text: "What problem was Nommi trying to solve?",
    category: "projects",
  },
  {
    id: "muselab-taught",
    number: "30",
    text: "What did MuseLab teach you?",
    category: "projects",
  },
  {
    id: "most-difficult",
    number: "31",
    text: "What project was most difficult?",
    category: "projects",
  },
  {
    id: "changed-most",
    number: "32",
    text: "Which project changed the most during development?",
    category: "projects",
  },
  {
    id: "redesign-today",
    number: "33",
    text: "What project would you redesign today?",
    category: "projects",
  },
  {
    id: "projects-common",
    number: "34",
    text: "What do your projects have in common?",
    category: "projects",
  },
  {
    id: "ironclad-work",
    number: "35",
    text: "What kind of work did you do at Ironclad?",
    category: "projects",
  },
  {
    id: "tesla-work",
    number: "36",
    text: "What did you work on at Tesla?",
    category: "projects",
  },
  {
    id: "research-vs-build",
    number: "37",
    text: "How do research and product engineering differ for you?",
    category: "research",
  },
  {
    id: "research-prototypes",
    number: "38",
    text: "What did you learn from building research prototypes?",
    category: "research",
  },
  {
    id: "differ-about",
    number: "39",
    text: "What is Differ?",
    category: "research",
  },
  {
    id: "poem-to-song",
    number: "40",
    text: "What is the Poem-to-Song project?",
    category: "research",
  },
  {
    id: "pomdp",
    number: "41",
    text: "What is the POMDP aid-allocation project about?",
    category: "research",
  },
  {
    id: "uncertainty",
    number: "42",
    text: "How do you deal with uncertainty in complex projects?",
    category: "research",
  },
  {
    id: "poetry-engineering",
    number: "43",
    text: "How are poetry and engineering connected for you?",
    category: "creative",
  },
  {
    id: "digital-physical",
    number: "44",
    text: "What makes digital work feel physical?",
    category: "creative",
  },
  {
    id: "archives-diagrams",
    number: "45",
    text: "Why are you attracted to visual systems that resemble archives, diagrams, or scientific records?",
    category: "creative",
  },
  {
    id: "imperfection",
    number: "46",
    text: "How do you use imperfection intentionally?",
    category: "creative",
  },
  {
    id: "dissecting",
    number: "47",
    text: "What does “dissecting myself” mean in the context of your portfolio?",
    category: "creative",
  },
  {
    id: "art-research",
    number: "48",
    text: "How do art and research influence each other?",
    category: "creative",
  },
  {
    id: "visual-trends",
    number: "49",
    text: "What kinds of visual trends do you dislike?",
    category: "creative",
  },
  {
    id: "interaction-over-decoration",
    number: "50",
    text: "Why do you prefer meaningful interaction over decoration?",
    category: "creative",
  },
  {
    id: "visitors-feel",
    number: "51",
    text: "What do you want visitors to feel after seeing your site?",
    category: "creative",
  },
  {
    id: "creativity-systems",
    number: "52",
    text: "How do you balance creativity and systems thinking?",
    category: "creative",
  },
  {
    id: "shaped-by",
    number: "53",
    text: "What books, ideas, or people have shaped you?",
    category: "creative",
  },
  {
    id: "creativity-translation",
    number: "54",
    text: "What does creativity mean to you?",
    category: "creative",
  },
  {
    id: "problems-enjoy",
    number: "55",
    text: "What kinds of problems do you want to work on?",
    category: "career",
  },
  {
    id: "work-environment",
    number: "56",
    text: "What kind of work environment helps you thrive?",
    category: "career",
  },
  {
    id: "better-at",
    number: "57",
    text: "What do you want to become better at?",
    category: "career",
  },
  {
    id: "currently-curious",
    number: "58",
    text: "What are you currently curious about?",
    category: "career",
  },
  {
    id: "eng-design-teams",
    number: "59",
    text: "How do you want engineering teams to work with design?",
    category: "career",
  },
  {
    id: "next-opportunity",
    number: "60",
    text: "What are you looking for in your next role?",
    category: "career",
  },
  {
    id: "prestige",
    number: "61",
    text: "What would you work on if prestige did not matter?",
    category: "career",
  },
  {
    id: "money-no-matter",
    number: "62",
    text: "What would you be working on if money didn't matter?",
    category: "career",
  },
  {
    id: "proudest",
    number: "63",
    text: "What are you proudest of?",
    category: "career",
  },
  {
    id: "meaningful-life",
    number: "64",
    text: "What makes a life feel meaningful to you?",
    category: "career",
  },
  {
    id: "insecure",
    number: "65",
    text: "What are you insecure about?",
    category: "personal",
  },
  {
    id: "misunderstand",
    number: "66",
    text: "What do people usually misunderstand about you?",
    category: "personal",
  },
  {
    id: "kind-of-friend",
    number: "67",
    text: "What kind of friend are you?",
    category: "personal",
  },
  {
    id: "recharge",
    number: "68",
    text: "How do you recharge?",
    category: "personal",
  },
  {
    id: "criticism",
    number: "69",
    text: "How do you handle criticism?",
    category: "personal",
  },
  {
    id: "wish-asked-more",
    number: "70",
    text: "What do you wish people asked you more often?",
    category: "personal",
  },
  {
    id: "without-titles",
    number: "71",
    text: "How would you describe yourself without using job titles?",
    category: "personal",
  },
  {
    id: "past-self",
    number: "72",
    text: "What advice would you give to your past self?",
    category: "personal",
  },
  {
    id: "amateur",
    number: "73",
    text: "What does amateurism mean to you?",
    category: "personal",
  },
  {
    id: "enjoy-reading",
    number: "74",
    text: "What do you enjoy reading?",
    category: "personal",
  },
  {
    id: "movies-stay",
    number: "75",
    text: "What kinds of movies stay with you?",
    category: "personal",
  },
  {
    id: "poem-think-about",
    number: "76",
    text: "Is there a poem you think about often?",
    category: "personal",
  },
  {
    id: "music-stayed",
    number: "77",
    text: "What music has stayed with you?",
    category: "personal",
  },
  {
    id: "favorite-names",
    number: "78",
    text: "Do you have favorite artists, photographers, software, or museums?",
    category: "personal",
  },
  {
    id: "actually-shirley",
    number: "79",
    text: "Are you actually Shirley?",
    category: "personal",
  },
  {
    id: "phone-number",
    number: "80",
    text: "What is Shirley’s phone number?",
    category: "personal",
  },
  {
    id: "never-discussed",
    number: "81",
    text: "What does Shirley think about a topic she has never discussed?",
    category: "personal",
  },
  {
    id: "decision-behalf",
    number: "82",
    text: "Can you make a decision on Shirley’s behalf?",
    category: "personal",
  },
  {
    id: "available-job",
    number: "83",
    text: "Is Shirley available for a job?",
    category: "personal",
  },
  {
    id: "something-private",
    number: "84",
    text: "Tell me something private about Shirley.",
    category: "personal",
  },
  {
    id: "salary",
    number: "85",
    text: "What salary would Shirley accept?",
    category: "personal",
  },
  {
    id: "like-me",
    number: "86",
    text: "Would Shirley like me personally?",
    category: "personal",
  },
  {
    id: "official-statement",
    number: "87",
    text: "Can I treat this answer as an official statement from Shirley?",
    category: "personal",
  },
  {
    id: "how-certain",
    number: "88",
    text: "How certain are you that Shirley would agree with this answer?",
    category: "personal",
  },
];

export function questionsForCategory(category: AskShirleyCategory): AskShirleyQuestion[] {
  if (category === "all") return ASK_SHIRLEY_QUESTIONS;
  return ASK_SHIRLEY_QUESTIONS.filter((q) => q.category === category);
}
