import type { WorkProject } from "./types";

export const workProjects: WorkProject[] = [
  {
    slug: "muselab",
    title: "MuseLab",
    role: "Designer & Developer",
    org: "Independent project",
    dates: "2025–2026",
    tags: ["ai-ml", "generative-systems", "writing", "nlp"],
    teaser: "A literary workshop dossier — interpretation over generation.",
    story: ["Immersive room."],
  },
  {
    slug: "echo",
    title: "Echo",
    role: "Designer & Developer",
    org: "CS146J · Stanford",
    dates: "2024–2025",
    collaborators: ["Clare Lei", "Rita Xiang"],
    tags: ["generative-systems", "nlp", "data-viz", "frontend", "writing"],
    teaser: "Words that continue breathing across five afterlives.",
    story: ["Immersive room."],
    liveUrl: "https://cs146j-finalproject.onrender.com/",
  },
  {
    slug: "nommi",
    title: "Nommi",
    role: "Co-creator",
    org: "CS278 · Stanford",
    dates: "Spring 2026",
    collaborators: ["Aditya Garg", "Alexis Young"],
    tags: ["social-computing", "frontend", "data-systems"],
    teaser: "Campus food knowledge that stays alive — scroll the phone.",
    story: ["Immersive phone world."],
    liveUrl: "https://cs278-food-recommender.vercel.app/login",
    githubUrl: "https://github.com/xinyuezhang-shirley/cs278FoodRecommender",
  },
  {
    slug: "tesla",
    title: "Tesla · Brake health",
    role: "Data Analyst Intern, ML & Data Engineering",
    org: "Tesla",
    dates: "Mar–Jun 2025",
    tags: ["ai-ml", "data-systems"],
    teaser: "Fleet telemetry as a living diagnostics bay.",
    story: ["Immersive dashboard world."],
  },
  {
    slug: "pwc",
    title: "PwC · Multi-agent RAG",
    role: "Software Engineering Intern",
    org: "PwC",
    dates: "Jun–Aug 2025",
    tags: ["ai-ml", "data-systems", "frontend"],
    teaser: "Knowledge retrieval as mission control.",
    story: ["Immersive console world."],
  },
  {
    slug: "ironclad",
    title: "Ironclad",
    role: "Software Engineering Intern",
    org: "Ironclad",
    dates: "Jun 2026 – Present",
    tags: ["data-systems", "ai-ml"],
    teaser: "Chat-native procurement into provenance-aware contract workflows.",
    story: ["Immersive pipeline world."],
  },
  {
    slug: "systems-signals",
    title: "NU Solar · Telemetry",
    role: "Software Team Lead",
    org: "NU Solar",
    dates: "2023–2025",
    tags: ["data-systems", "data-viz"],
    teaser: "CAN bus signals for drivers and diagnosticians.",
    story: ["Quiet archival chapter."],
  },
];
