import type { WorkProject } from "./types";

export const workProjects: WorkProject[] = [
  {
    slug: "muselab",
    title: "MuseLab",
    role: "Designer & Developer",
    org: "Independent project",
    dates: "2025–2026",
    tags: ["ai-ml", "generative-systems", "writing", "nlp"],
    teaser: "A literary workshop dossier — interpretation over generation.",
    story: ["Immersive room."],
    catalogId: "W-01",
    status: "Prototype",
    type: "Independent",
    year: "2025–26",
    duration: "18 mo",
    teamSize: "1",
    discipline: ["Generative systems", "NLP"],
    signals: ["Literary analysis", "Multi-agent critique", "Interpretation stack"],
    tools: ["React", "TypeScript"],
    related: [{ slug: "echo", note: "Related" }],
  },
  {
    slug: "echo",
    title: "Echo",
    role: "Designer & Developer",
    org: "CS146J · Stanford",
    dates: "2024–2025",
    collaborators: ["Clare Lei", "Rita Xiang"],
    tags: ["generative-systems", "nlp", "data-viz", "frontend", "writing"],
    teaser: "Words that continue breathing across five afterlives.",
    story: ["Immersive room."],
    liveUrl: "https://cs146j-finalproject.onrender.com/",
    catalogId: "W-02",
    status: "Course Project",
    type: "Interactive system",
    year: "2024–25",
    duration: "10 wk",
    teamSize: "3",
    discipline: ["Narrative design", "Creative coding"],
    signals: ["Interactive poetry", "WebGL afterlives", "Semantic visualization"],
    tools: ["React", "WebGL", "NLP"],
    related: [{ slug: "muselab", note: "Built alongside" }],
  },
  {
    slug: "nommi",
    title: "Nommi",
    role: "Co-creator",
    org: "CS278 · Stanford",
    dates: "Spring 2026",
    collaborators: ["Aditya Garg", "Alexis Young"],
    tags: ["social-computing", "frontend", "data-systems"],
    teaser: "Campus food knowledge that stays alive — scroll the phone.",
    story: ["Immersive phone world."],
    liveUrl: "https://cs278-food-recommender.vercel.app/login",
    githubUrl: "https://github.com/xinyuezhang-shirley/cs278FoodRecommender",
    catalogId: "W-03",
    status: "Prototype",
    type: "Course product",
    year: "2026",
    duration: "10 wk",
    teamSize: "3",
    discipline: ["Social computing", "Community systems"],
    signals: ["Social computing", "Live recommendation", "Mobile-first UI"],
    tools: ["React", "TypeScript", "Supabase"],
  },
  {
    slug: "tesla",
    title: "Tesla · Brake health",
    role: "Data Analyst Intern, ML & Data Engineering",
    org: "Tesla",
    dates: "Mar–Jun 2025",
    tags: ["ai-ml", "data-systems"],
    teaser: "Fleet telemetry as a living diagnostics bay.",
    story: ["Immersive dashboard world."],
    catalogId: "W-04",
    status: "Archive",
    type: "Internship",
    year: "2025",
    duration: "4 mo",
    teamSize: "Team",
    discipline: ["ML engineering", "Fleet systems"],
    signals: ["Fleet telemetry", "Brake diagnostics", "Production data"],
    tools: ["Python", "SQL", "Spark"],
  },
  {
    slug: "pwc",
    title: "PwC · Multi-agent RAG",
    role: "Software Engineering Intern",
    org: "PwC",
    dates: "Jun–Aug 2025",
    tags: ["ai-ml", "data-systems", "frontend"],
    teaser: "Knowledge retrieval as mission control.",
    story: ["Immersive console world."],
    catalogId: "W-05",
    status: "Archive",
    type: "Internship",
    year: "2025",
    duration: "3 mo",
    teamSize: "Team",
    discipline: ["Enterprise AI", "Information retrieval"],
    signals: ["Multi-agent RAG", "Azure AI Search", "Citation grounding"],
    tools: ["Langflow", "Azure", "React"],
  },
  {
    slug: "ironclad",
    title: "Ironclad",
    role: "Software Engineering Intern",
    org: "Ironclad",
    dates: "Jun 2026 – Present",
    tags: ["data-systems", "ai-ml"],
    teaser: "Chat-native procurement into provenance-aware contract workflows.",
    story: ["Immersive pipeline world."],
    catalogId: "W-06",
    status: "Production",
    type: "Internship",
    year: "2026",
    duration: "Ongoing",
    teamSize: "Team",
    discipline: ["Agent orchestration", "Contract systems"],
    signals: ["Multi-agent systems", "LLM orchestration", "Production workflows"],
    tools: ["TypeScript", "Python", "RAG"],
  },
  {
    slug: "systems-signals",
    title: "NU Solar · Telemetry",
    role: "Software Team Lead",
    org: "NU Solar",
    dates: "2023–2025",
    tags: ["data-systems", "data-viz"],
    teaser: "CAN bus signals for drivers and diagnosticians.",
    story: ["Quiet archival chapter."],
    catalogId: "W-07",
    status: "Archive",
    type: "Leadership",
    year: "2023–25",
    duration: "2 yr",
    teamSize: "Lead",
    discipline: ["Embedded systems", "Telemetry"],
    signals: ["CAN bus", "Driver displays", "Diagnostic tooling"],
    tools: ["C++", "Python", "Qt"],
  },
];

export function workBySlug(slug: string): WorkProject | undefined {
  return workProjects.find((p) => p.slug === slug);
}
